spring:
  application:
    name: passafe

  datasource:
    # Ajuste para SQL Server (SQL Express)
    url: jdbc:sqlserver://localhost:1433;databaseName=passafe;encrypt=true;trustServerCertificate=true
    username: sa
    password: SUASENHA_AQUI
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

# Chave de Criptografia AES-256 (32 caracteres)
passafe:
  encryption:
    key: ${PASSAFE_SECRET_KEY:12345678901234567890123456789012}
