# Configuração do Banco de Dados H2 (Ideal para testes e desenvolvimento rápido)
spring.datasource.url=jdbc:h2:mem:passafedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# O Hibernate detectará automaticamente o dialeto H2, não é necessário forçar o do SQL Server aqui.

# Chave de Criptografia AES-256 (32 caracteres)
passafe.encryption.key=12345678901234567890123456789012
