# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/passafe
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chave de Criptografia AES-256 (Deve ter exatamente 32 caracteres)
passafe.encryption.key=12345678901234567890123456789012
