# Configuração do Banco de Dados H2 (Sem erros de conexão)
spring.datasource.url=jdbc:h2:mem:passafedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Chave de Criptografia AES-256 (32 caracteres)
passafe.encryption.key=12345678901234567890123456789012
passafe.jwt.secret=1234567890123456789012345678901212345678901234567890123456789012
