spring:
  application:
    name: passafe

  datasource:
    url: jdbc:h2:mem:passafedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Credenciais para acessar o Swagger (Login da Página de Documentação)
swagger:
  user: admin
  password: admin123

# Chaves de Segurança
passafe:
  encryption:
    key: ${PASSAFE_SECRET_KEY:12345678901234567890123456789012}
  jwt:
    secret: 1234567890123456789012345678901212345678901234567890123456789012
